name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build and Prepare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    name: Deploy (placeholder)
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          docker build -t your-docker-username/chsw:latest .
          docker push your-docker-username/chsw:latest
